#pragma once


// WIDGET PROPERTIES
int OFFSET_X = 50;
int OFFSET_Y = 50;
float SCALE = 10;
float PAINTING_RADIUS = 2;

// DEFAULT PROPERTIES
float DEFAULT_MASS = 10.;
float DEFAULT_CHARGE = 0.;
float DEFAULT_LENGTH_SCALE = 50.;
float DT = 0.01;

// VDW POTENTIAL PROPERTIES
float VDW_RADIUS = 10.;
float VDW_PRE_FACTOR = 1.;

// HARMONIC POTENTIAL PROPERTIES
float R0 = 45.;
float K = 1.;
